services:

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    image: python-fastapi-mongo
    env_file:
      - ./app/.env
    ports:
      - "8005:8005"
    command: python ./main.py
    container_name: python-fastapi-mongo

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - app