services:

  python-fastapi-mongo:
    build:
      context: ./
      dockerfile: Dockerfile
    image: python-fastapi-mongo
    env_file:
      - .env
    ports:
      - "8005:8005"
    command: python ./main.py
    container_name: python-fastapi-mongo